# Generated by Django 4.2.7 on 2023-11-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('usuario_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('trabajador_tipo_documento', models.CharField(max_length=100)),
                ('trabajador_path_documento', models.CharField(default='PATH/noNe', max_length=255)),
                ('trabajador_nacionalidad', models.CharField(default='No Especificado', max_length=100)),
                ('trabajador_fecha_nacimiento', models.DateField()),
                ('trabajador_ubigeo', models.CharField(default='No Especificado', max_length=255)),
                ('trabajador_telefono', models.CharField(max_length=100)),
                ('trabajador_sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No Especificado', 'No Especificado')], default='No Especificado', max_length=15)),
                ('trabajador_estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'), ('Conviviente', 'Conviviente'), ('No Especificado', 'No Especificado')], default='No Especificado', max_length=15)),
                ('trabajador_path_doc_estado_civil', models.CharField(default='PATH/noNe', max_length=255)),
                ('trabajador_fecha_ingreso_sistema', models.DateField()),
                ('trabajador_fecha_ingreso', models.DateField()),
                ('trabajador_edad', models.IntegerField()),
                ('trabajador_record', models.DecimalField(decimal_places=2, max_digits=20)),
                ('trabajador_exp_previa', models.DecimalField(decimal_places=2, max_digits=20)),
                ('trabajador_total_anios_exp', models.DecimalField(decimal_places=2, max_digits=20)),
                ('usuario_relacionado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.CharField(max_length=20)),
                ('sueldo_valor_basico', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sueldo_asigfam_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sueldo_asignacion_familiar', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sueldo_bono_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sueldo_monto_bono', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sueldo_mensual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sueldo_anual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajador')),
            ],
        ),
    ]
