# Generated by Django 4.2.7 on 2023-11-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cuentabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.CharField(max_length=20)),
                ('direccion_pais', models.CharField(max_length=255)),
                ('direccion_departamento', models.CharField(max_length=255)),
                ('direccion_provincia', models.CharField(max_length=255)),
                ('direccion_distrito', models.CharField(max_length=255)),
                ('direccion_detalle', models.CharField(max_length=255)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajador')),
            ],
        ),
    ]
