# Generated by Django 4.2.7 on 2023-11-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('NE', 'No Especificado')], default='No Especificado', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_telefono',
            field=models.CharField(default='999888777', max_length=50),
            preserve_default=False,
        ),
    ]
