# Generated by Django 4.2.7 on 2023-11-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usuario_usuario_sexo_usuario_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='cuentabancaria',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='sueldo',
            name='usuario_id',
        ),
    ]
