# Generated by Django 4.2.7 on 2023-11-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_contrato_usuario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='usuario_id',
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='usuario_relacionado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario'),
        ),
    ]
