# Generated by Django 4.2.7 on 2023-11-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_trabajador_usuario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='usuario_id',
        ),
    ]
